version: "3.8"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    expose:
      - "4000"
    environment:
      - DEBUG=true
    env_file: ./.env
    command: python src/server.py
    depends_on:
      - mongodb_container

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules          # Add anonymous volume for node_modules
    env_file: .env
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:4000/
      # - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      # - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    ports:
      - "3000:3000"
    command: npm run dev 
    depends_on:
      - backend

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./webapp:/app
      - /app/node_modules
    env_file: .env
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:4000/
    ports:
      - "3001:3001"
    command: npm run dev 
    depends_on:
      - backend

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "5000:27017"
    
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
